"""Identifiers for objects on the CAN bus(es) and physical robot dimensions.

Note: Swerve drivetrain configuration is now in generated/tuner_constants.py
which is designed to be regenerated by Phoenix Tuner X's Swerve Project Generator.
"""

from enum import IntEnum
from typing import Final

import wpimath.units as units


class CANID(IntEnum):
    """IDs for items on the CAN bus.

    Note: Swerve motor and encoder CAN IDs are now in generated/tuner_constants.py.
    """

    # Other motors (non-swerve)
    SHOOTER_MOTOR = 15


class RobotDimension:
    """Physical dimensions and locations of robot components.

    Note: Swerve module locations are now in generated/tuner_constants.py.
    """

    # Shooter dimensions
    SHOOTER_Z: Final[units.meters] = 0.421
    SHOOTER_MAX_ANGLE: Final[units.radians] = units.degreesToRadians(34.0)


class ControllerPort:
    """USB ports for controllers."""

    DRIVER_CONTROLLER: Final[int] = 0
    OPERATOR_CONTROLLER: Final[int] = 1
